### ISSUE TITLE
minifyEnabled

### ISSUE THREAD

**Issue by getActivity** [thegrizzlylabs/sardine-android#16] opened 2018-10-28 11:01 UTC
Hello, this project is very good, but a little problem
minifyEnabled false: no problem
minifyEnabled true: there is an inability to call Sardine.list(url)

    W/System.err: java.io.IOException: Not a valid DAV response
    at com.thegrizzlylabs.sardineandroid.util.SardineUtil.unmarshal(Unknown Source:14)
    W/System.err:     at com.thegrizzlylabs.sardineandroid.impl.handler.MultiStatusResponseHandler.getMultistatus(Unknown Source:2)
    at com.thegrizzlylabs.sardineandroid.impl.handler.MultiStatusResponseHandler.handleResponse(Unknown Source:29)
    at com.thegrizzlylabs.sardineandroid.impl.handler.ResourcesResponseHandler.handleResponse(Unknown Source:5)
    at com.thegrizzlylabs.sardineandroid.impl.handler.ResourcesResponseHandler.handleResponse(Unknown Source:0)
    at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.execute(Unknown Source:10)
    at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.propfind(Unknown Source:53)
    at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.list(Unknown Source:15)
    at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.list(Unknown Source:1)
    at com.thegrizzlylabs.sardineandroid.impl.OkHttpSardine.list(Unknown Source:1)
    at com.hjq.md.webdav.WebDavHelper.getPathList(Unknown Source:78)
    at com.hjq.md.ui.activity.BackupActivity$1.run(Unknown Source:18)
    at java.lang.Thread.run(Thread.java:764)

**Comment by guillaume-tgl** [comment] 2018-10-28 14:03
Can you provide the URL you call to be able to reproduce?

**Comment by getActivity** [comment] 2018-10-29 02:32
private static final String DEFAULT_HOST = "http://dav.jianguoyun.com/dav";

**Comment by getActivity** [comment] 2018-10-29 02:33
But this problem comes after code confusion

**Comment by drakeet** [comment] 2018-10-29 03:05
I am using this library and the jianguoyun.com server and `minifyEnabled = true` without any extra proguard rule for it. It works well. I think the inner consumer proguard file is well set for it.

Are you using maven to import this libary? If no, you should include the inner consumer proguard file by yourself: 

```proguard
## SimpleXml
-dontwarn org.simpleframework.xml.stream.**
-keep class org.simpleframework.xml.**{ *; }
-keepclassmembers,allowobfuscation class * {
    @org.simpleframework.xml.* <fields>;
    @org.simpleframework.xml.* <init>(...);
}

## Sardine Android model classes: needed for XML serialization
-keep class com.thegrizzlylabs.sardineandroid.model.**{ *; }

## OkHTTP
-dontwarn okhttp3.internal.platform.ConscryptPlatform
```

**Comment by getActivity** [comment] 2018-10-29 03:16
@drakeet Thank you, but there are still questions

**Comment by guillaume-tgl** [comment] 2018-10-30 09:29
Could you paste your `build.gradle`?

**Comment by getActivity** [comment] 2018-10-30 09:44
debug {
            zipAlignEnabled true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

**Comment by getActivity** [comment] 2018-12-28 10:34
Please help  give me a look with this problem

**Comment by guillaume-tgl** [comment] 2018-12-29 13:48
It seems like you still have an obfuscation problem but the library proguard file seems correct since it already excludes classes in `com.thegrizzlylabs.sardineandroid.model` from being obfuscated. Could you share your project or a minimal project where the issue can be reproduced?

**Comment by guillaume-tgl** [comment] 2019-01-07 12:22
I'm closing for now, but let me know if you can reproduce this issue in a minimal project and share the code.

**Closed by guillaume-tgl** 2019-01-07 12:22 UTC
